WIP: V4R update
strands-project/v4r_ros_wrappers pull request #39
Opened 2017-02-08 08:55 UTC by ToMadoRe

associated update to https://github.com/strands-project/v4r/pull/73

2017-02-08 10:06 UTC, marc-hanheide requested changes
the dependencies need to be fixed

2017-02-08 10:06 UTC, marc-hanheide commented on temporal_filtering/package.xml
> +  <build_depend>opencv</build_depend>
This is not a valid rosdep key. This is what failed in https://lcas.lincoln.ac.uk/jenkins/job/pr-indigo-v4r_ros_wrappers/49/ You may want to use `cv_bridge` instead. Also below in `<run_depend>`

2017-02-08 10:06 UTC, marc-hanheide commented on temporal_filtering/package.xml
> +  <build_depend>opencv</build_depend>
@ToMadoRe I think you ought to be fixing this.

2017-02-08 11:22 UTC, marc-hanheide approved these changes

2017-05-05 13:16 UTC, ToMadoRe commented
retest this please

2017-05-05 13:52 UTC, merged